### ISSUE TITLE
Include several objective functions with DREAM

### ISSUE THREAD

**Issue by zutn** [zutn/acme#25]
DREAM uses this weird objective function, can Spotpy still be used to calculate other objective functions in the progress? For example Klingt Gupta, so in the End one can better compare stuff with ACME?

**Comment by thouska** [comment]
yes, thats possible, e.g. like this:

    def objectivefunction(self,simulation,evaluation):
        like1 = spotpy.likelihoods.gaussianLikelihoodMeasErrorOut(evaluation,simulation)
        like2 = spotpy.objectivefunctions.kge(evaluation,simulation)
        return [like1,like2]


And just for the record, the DREAM objectivefunction is not weird, just different ;)

**Comment by zutn** [comment]
Thanks for the quick replay, did not really think that anyone but me would read this^^
I figured this could be done the way you laid out, but I knowing it for sure is quite helpful!

For me the DREAM objectivefunction will remain weird until I understand what it does ;)

**Comment by thouska** [comment]
The gaussian likelihood function is not too complex. From the mathematically compexety similar to KGE:
 
    p = -n/2\\log(\\sum_{t=1}^n e_t(x)^2)

with e_t = observation - simulation, and n = len(simulation). So more ore less, just the negative log of the sum of the squared residuals. The value is allways negative. The closer to zero the better is the fit.

**Comment by zutn** [comment]
Ah nice. Thanks.
You mean spotpy.likelihoods.gaussianLikelihoodMeasErrorOut?

**Comment by thouska** [comment]
exactly

**Comment by florianjehn** [comment]
For now acme will use Latin Hypercube Sampling. Therefore, this is closed. Might need reevaluation in future.
