### ISSUE TITLE
Files are not read on Travis

### ISSUE THREAD

**Issue by zutn** [zutn/ACME#26]
Build keeps failing because Travis cannot find the right files. 
How do I tell Travis where the files are to be found?
https://travis-ci.org/zutn/ACME/jobs/286938074

**Comment by thouska** [comment]
This should work, if you include your input test files into your setup.py of ACME:

  package_data={
   'acme.tests': ['*'],
},

**Comment by zutn** [comment]
Solved it with:
http://flask.pocoo.org/docs/0.12/patterns/distribute/#distributing-resources
